# Generated by Django 5.0.6 on 2024-06-07 15:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_register_address'),
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fee',
            name='register2',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='accounts.register'),
        ),
        migrations.CreateModel(
            name='Attendence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('percentage', models.IntegerField()),
                ('attend', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='accounts.register')),
            ],
        ),
    ]
