# Generated by Django 5.0.6 on 2024-06-07 16:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_register_address'),
        ('students', '0002_alter_fee_register2_attendence'),
    ]

    operations = [
        migrations.RenameField(
            model_name='attendence',
            old_name='attend',
            new_name='register4',
        ),
        migrations.RenameField(
            model_name='fee',
            old_name='register2',
            new_name='register3',
        ),
        migrations.RenameField(
            model_name='marks',
            old_name='register1',
            new_name='register2',
        ),
        migrations.RemoveField(
            model_name='student_id',
            name='register',
        ),
        migrations.AddField(
            model_name='student_id',
            name='register1',
            field=models.OneToOneField(default=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.register'),
            preserve_default=False,
        ),
    ]
