# Generated by Django 5.0.6 on 2024-06-11 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0005_attendence_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendence',
            name='days',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='attendence',
            name='tick',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='attendence',
            name='percentage',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='marks',
            name='marks',
            field=models.IntegerField(default=0),
        ),
    ]
