# Generated by Django 5.0.6 on 2024-06-11 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0006_attendence_days_attendence_tick_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendence',
            name='tick',
            field=models.DateTimeField(),
        ),
    ]
