# Generated by Django 5.0.6 on 2024-06-11 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0007_alter_attendence_tick'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendence',
            name='tick',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
