# Generated by Django 5.0.6 on 2024-06-05 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Register',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('mobile_number', models.CharField(max_length=12)),
                ('email', models.EmailField(default='email', max_length=254)),
                ('address', models.TextField()),
                ('class_name', models.CharField(default='admin', max_length=10)),
                ('course', models.CharField(default='admin', max_length=10)),
                ('username', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=10)),
                ('confirm_password', models.CharField(max_length=10)),
                ('user_type', models.CharField(max_length=10)),
            ],
        ),
    ]
